### ISSUE TITLE
Provide way to pass "context" to BrailleTranslationResult functions

### ISSUE THREAD

**Issue by bertfrees** [brailleapps/dotify.api#13]
where "context" = info about the preceding and following segment.

This is needed if you want the line breaking of multiple consecutive segments to be correct. If line breaking is performed on the different segments independently, it may happen that a line is broken exactly in between two segments while it isn't always allowed.

The context could look something like

```java
PrecedingSegmentInfo preceding, FollowingSegmentInfo following
```

where
```java
interface PrecedingSegmentInfo {
    public boolean endsWithBreakOpportunity();
    public boolean endsWithCollapsibleSpace();
}

interface FollowingSegmentInfo {
    public boolean startsWithBreakOpportunity();
    public boolean startsWithCollapsibleSpace();
}
```

and `BrailleTranslationResult` would implement `PrecedingSegmentInfo, FollowingSegmentInfo`

Another use case (mainly for illustration, because the current solution kind of works with some workarounds) could be to leave the white space normalisation entirely up to the braille translator. For example, right now the Dotify formatter strips leading white space from blocks because this can't be left up to the translator. When passing the context this would become possible.

**Comment by bertfrees** [comment]
See https://github.com/sbsdev/pipeline/commit/12351991a32e41314461733d0536cfbf1ba3fb7e

**Comment by bertfrees** [comment]
After discussing it today with Joel I realized that the suggested solution with PrecedingSegmentInfo and FollowingSegmentInfo doesn't help much. It is not enough to know whether the next segments starts with a break opportunity, you should actually know where the next break opportunity is.

Talking to Joel also gave me a different view on [my current solution](https://github.com/sbsdev/pipeline/commit/4be1beecc46e45a03bbbd55b977ef94b7b509e85). Actually it would be much smarter to invert the order of the nextTranslatedRow and getTranslatedRemainder calls. This way the meaning of the API doesn't have to change. In this case Joel would accept the patch.

I also just realized that the current solution breaks non-standard hyphenation. (Note to self: add a test to demonstrate this.) The new solution would not.

We also talked about the possibility of adding a "peekNextTranslatedRow" method, but that is not even needed.

**Comment by joeha480** [comment]
Perhaps related to #29?

**Comment by bertfrees** [comment]
Totally.

**Comment by kalaspuffar** [comment]
This is fixed.
