### ISSUE TITLE
Export "metadata" about the conversion

### ISSUE THREAD

**Issue by bertfrees** [brailleapps/dotify.api#14]
Some metadata about the conversion would be useful to have. I'm talking about for example:

- The start and end page number of each section.
- The start and end values of each marker class in each section. (The idea of this is to be able to compute the print page number range of each volume.)
- ...

I'm not sure how the metadata would be exported. Some metadata would probably be suitable for storing in the PEF itself, but for other metadata this is not the case. So maybe just an additional output document, or possibly some callback function in Java?

This is a request from Dedicon, who would like to store some metadata in a file, including the braille and print page number ranges.

**Comment by PaulRambags** [comment]
At Dedicon I have solved the issue of obtaining metadata in a different way. I will close this issue.
